name = "PLSRegressor"
uuid = "e010f91f-06b9-52b3-bed3-bb1da186bddc"
keywords = ["Partial Least Squares", "machine learning", "artificial intelligence", "Regression", "Multivariate Statistics", "Statistics"]
license = "MIT"
desc = "A Partial Least Squares Regressor package. Contains PLS1, PLS2 and Kernel PLS2 NIPALS algorithms. Can be used mainly for regression."
version = "1.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "^1"

[extras]
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"

[targets]
test = ["Test", "Random", "MLJBase", "MLJ"]
