name = "PLSRegressor"
uuid = "e010f91f-06b9-52b3-bed3-bb1da186bddc"
keywords = ["Partial Least Squares", "machine learning", "artificial intelligence", "Regression", "Multivariate Statistics", "Statistics"]
license = "MIT"
desc = "A Partial Least Squares Regressor package. Contains PLS1, PLS2 and Kernel PLS2 NIPALS algorithms. Can be used mainly for regression."
version = "1.1.1"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JLD = "0.9.2"
julia = ">= 1.1"
